# Web Server
web:
    build: ./
    ports:
        - "50082:3000"
    volumes:
        - ./:/data:cached
    command: yarn start
    env_file:
        - .docker.env
        - .docker.local.env

# Command Line Tools
cli:
    build: ./
    volumes:
        - ./:/data:cached
    env_file:
        - .docker.env
        - .docker.local.env
